site_name: Snowem Documentation
pages:
  - Get Started: index.md
  - API Reference:
    - Snowem Setup: sdk.md
    - Channel Management: channelmgr.md
    - Stream Management: streammgr.md
  - Resources: resources.md
theme: readthedocs
